apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: node-app
  name: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - image: gbrotas/eks-app:1.0.0
          name: node-app
          resources:
            requests:
              cpu: 500m
              memory: 256Mi 
            limits:
              cpu: 1000m
              memory: 512Mi
    